### PR TITLE
jupyter_notebook_version

### PR DESCRIPTION
**Pull request by the-zebulan**
Here is a list of the changes I made:
- Most notably, I converted your README file to a Jupyter Notebook. This gives the ability to use Markdown and have runnable Python code as well. If a user wants to download it, they can edit and run the code examples on their own computer. It is also possible to view it on GitHub but the notebook is read-only.
- Currently, the code examples can be run using both Python 2 & 3. I imported `print_function` from `__future__` so the code examples could use the print function in both versions of Python. If you didn't want to use the print function (or statement in Python 2) you could always change the examples to use `assert`. Example: `assert 1 + 1 == 2`. If there is an error, it would be displayed below the corresponding cell.
- I added a couple other ways to reverse a list and one other way to reverse a string.
- I added a bit of explanation about the slice syntax to your copy section. I also added a couple examples using `copy.copy()` and `copy.deepcopy()`.
- I added a list comprehension version of creating a list out of a string.
- I modified your `for/else` loop example. It seemed too vague to me as an example of why someone would want to use `else`. I think my changes make it clear why `for/else` is used.
- I added two small example on list comprehensions. The first is the classic list comprehension to get only even numbers. The second example shows how to write a nested for loop. I added that because some people get confused as to the order of arguments in a nested list comprehension. Hopefully that is a clear example.

---

I raised an issue on your original repo detailing some of these things (I'll probably go and close it now). I saw you fixed the variable names (nice!) and I thought maybe it would be better for you to see an example of the Jupyter Notebook.

It is up to you which direction you want your python-tips repo to go. You can choose to keep it as a markdown file or switch to Jupyter notebook that has markdown AND runnable code (with syntax highlighting).

Either way, good luck!

### CODE REVIEW

**Comment by smoqadam** [comment]
Hi
Thanks for your contributing. I'm glad to see your suggestion and useful changes.I saw your issue before but I don't have enough time to answer it, just applied your changes.
Actually I'm new to Python and I have some questions. 
If I want to add a new section, do I have to edit both README and Jupyter Notebook? if yes how can I do this? 
thanks

**Comment by the-zebulan** [comment]
You are correct, that is the problem with having two different versions of the same thing. Right now you would have to edit both.

I didn't want to delete your README in case you didn't want to use the Jupyter notebook version. Basically, it comes down to a choice of the markdown file or the notebook. I wanted to leave that decision up to you.

If you choose to go with the notebook, you should probably just modify your README to be a standard description for the python-tips repo and then do the editing of the tips inside the Jupyter notebook.

**Comment by smoqadam** [comment]
Thanks
Could you please apply the changes to the README file as well as Jupyter Notebook?
I think its good if we have both README and Jupyter Notebook. But maybe it's hard to edit and contributing for others. README has more readability and easy to use.

**Comment by the-zebulan** [comment]
Sure, I can apply the changes to README. I think it would be better to just choose one though.

How about I just delete the Jupyter notebook but apply the changes to the README? I can't think of a way to update them both at the same time (there might be a way, I just don't know). It just doesn't seem right to make people have to edit two files.

[[D]on't [R]epeat [Y]ourself](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

**Comment by smoqadam** [comment]
Yes that's right. So please send a pr after apply the changes.

**Comment by the-zebulan** [comment]
Ok, I'll close this one and send you a different pull request when I'm done.

I'm heading to bed though, so it won't be for at least 8 hours!

**Comment by smoqadam** [comment]
Hey 
I'm waiting for your PR. if you don't have enough time please let me know then I'll added your tips.
thanks for contributing.

**Pull request closed without merging**
