### PR TITLE
Added more tips/examples, removed print statements

### PR DESCRIPTION
**Pull request by the-zebulan**
Sorry for the delay, I got busy at work. I applied the changes to the README this time!
- Added more tips/examples, removed print statements

### CODE REVIEW

**Comment by smoqadam** [comment]
I think your examples it's not clear for beginners. please change the examples to classic way and use `print` for show outputs. as far as possible don't change the previous examples, just add additional info if needed. 
thanks

**Comment by the-zebulan** [comment]
I read your response and made some changes based on a compromise. Here are a few reasons why I made the changes that I did.

You mention that the examples are not clear for beginners but I tried to make them very simple. I don't agree that putting `print` statements is the best way to show the output. The reason is the difference between Python 2's `print 'hello'` and Python 3's `print('hello')`. Also, if someone is beginning to learn Python nowadays, it is recommended they begin using Python 3. Your example outputs weren't uniform across the document. Some were on the same line as the example, some were below.
- In an attempt to compromise, what I did was use the Python interpreter to show the output. This way, it doesn't matter if a beginner is using Python 2 or 3 because the interpreter (lines starting with `>>>`) is common to both Python 2 and 3. Less confusion for beginners. They can type the examples in their own interpreter and test the results for themselves.

You asked me to not change the previous examples but the only changes I have made are very simple things like adding in additional examples and proper spacing in lists.
- Example: `['a','b','c'] -> ['a', 'b', 'c']`. Try typing in `>>> ['a','b','c']` or `>>> list('abc')` in a Python interpreter and you will see that Python outputs them with proper spacing between each item in the list.
- Your example with the quote `"Considered as one of the weirdest syntax to copy elements"` didn't seem very helpful to beginners. I changed that to explain what that syntax means. To help beginners!
- The reason I changed your ternary example was it didn't seem clear (especially to beginners) because the output and the condition look the same.  
  - I just thought an example like `10 if 1 + 1 == 2 else 20` made it clearer how the operation works.

I really think these contributions are helpful to your repo. They help to enforce a common style across the whole document and they are also compatible with Python versions 2 & 3. Hopefully you now understand why I made these changes, thanks!

**Comment by the-zebulan** [comment]
Also, your current `for/else` example is broken. It has two else statements (won't even run it raises a `SyntaxError`) and two prints are functions `print('something')` and one is a statement `print 'something'`. These are the types of issues that will confuse beginners!

Issues like this would not come up if you would use the examples and the style that is in my pull request.

**Comment by the-zebulan** [comment]
If you want, I can add in the copying of a list with extend that you just merged in.

**Pull request closed without merging**
